controllers:
    resource: ../../src/Controller/
    type: annotation

admin_controllers:
    resource: ../../src/Controller/Admin/
    type: annotation
    # toutes les url des routes definies dans src/Controller/Admin
    # commence par /admin
    prefix: /admin


kernel:
    resource: ../../src/Kernel.php
    type: annotation
